name: GitHub Breakout

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cyprieng/github-breakout@main
        with:
          github_username: ${{ github.repository_owner }}
