name: GitHub Breakout

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: cyprieng/github-breakout@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          mkdir -p images
          mv breakout.svg images/breakout-light.svg
          mv breakout-dark.svg images/breakout-dark.svg
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "update breakout" -a
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
